import type { Metadata } from "next";
import ChakraProviderWrapper from "@/components/Wrapper/ChakraProvider";
import Layout from "@/components/Wrapper/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProviderWrapper>
          <Layout>{children}</Layout>
        </ChakraProviderWrapper>
      </body>
    </html>
  );
}
